### ISSUE TITLE
Hello, may I ask if you have added code to project point clouds onto corresponding images based on true and predicted values？Thanks!

### ISSUE THREAD

**Issue by rainoverthere** [WHU-USI3DV/CoFiI2P#10]
A closed issue discussed this and there is a link, but the codes cannot be found now.

**Comment by martin-liao** [comment]
Thanks for your interest. We will provide the projection code later.

**Comment by martin-liao** [comment]
[link](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/vis_nuscenes_pose.ipynb)

**Comment by rainoverthere** [comment]
OK，thanks!

**Comment by martin-liao** [comment]
Since the problem has been resolved, I will close the issue.
