### ISSUE TITLE
The meaning of several symbols in the paper

### ISSUE THREAD

**Issue by YhQIAO** [WHU-USI3DV/CoFiI2P#11]
Thank you for your inspiring work.
While reading the paper, there are two symbols (delta_pos and delta_neg) in the loss function section that seem to have no detailed explanation. What do they mean?
![screenshoot_2024-09-06 223630](https://github.com/user-attachments/assets/27d5b5b9-c792-48d6-928f-eaddc385e916)

**Comment by martin-liao** [comment]
Please refer to [Circle loss](https://openaccess.thecvf.com/content_CVPR_2020/html/Sun_Circle_Loss_A_Unified_Perspective_of_Pair_Similarity_Optimization_CVPR_2020_paper.html) for details.
