### ISSUE TITLE
error when run evaluation

### ISSUE THREAD

**Issue by YhQIAO** [WHU-USI3DV/CoFiI2P#12]
after proprocessing unscene test dataset and run evaluation.py and get this error
![image](https://github.com/user-attachments/assets/206e4992-c508-425a-8aae-1a7343d3201b)

**Comment by YhQIAO** [comment]
![image](https://github.com/user-attachments/assets/26ead688-409b-4577-b83e-bed51f01cacb)
it seems that the dimension of two tensor dont match

**Comment by YhQIAO** [comment]
![image](https://github.com/user-attachments/assets/2ae18902-1974-4710-8efa-98793ebd0e7d)
after i change the number in model/network.py line 18 and 19(opt.img_H / 32 ...) original is 8, it works
but i wonder whether there are some mistakes in tensor dimension and it may lead to wrong result?

**Comment by YhQIAO** [comment]
Running train. py also has an issue on this line, with a tensor dimension mismatch error

**Comment by martin-liao** [comment]
Thanks for your interest. I am checking the code now.

**Comment by martin-liao** [comment]
> ![image](https://private-user-images.githubusercontent.com/49469609/365318787-2ae18902-1974-4710-8efa-98793ebd0e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NzcxMzksIm5iZiI6MTcyNTY3NjgzOSwicGF0aCI6Ii80OTQ2OTYwOS8zNjUzMTg3ODctMmFlMTg5MDItMTk3NC00NzEwLThlZmEtOTg3OTNlYmQwZTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAyNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYTI2YWE3OTg0ZjU1OTEyYTJjYWY3ZGRiNjdkMjgxNjk1YzM0Mjg4ZDA2YTM3NjJkZTdiNzQzZjQ2ODI1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ON7OdKek-FfGiIqKsX9OB_K9COKOUZa8wTaaqmgvn_A) after i change the number in model/network.py line 18 and 19(opt.img_H / 32 ...) original is 8, it works but i wonder whether there are some mistakes in tensor dimension and it may lead to wrong result?

yes, The modification would lead to a wrong result.

**Comment by martin-liao** [comment]
I have checked the evaluation code. It seems that everything is right.
![Screenshot from 2024-09-07 10-50-09](https://github.com/user-attachments/assets/5117f33e-e98c-477d-b9ef-885c6e1287bd)
Could you please provide the processed data? An incorrect input data shape might cause the issue.

**Comment by YhQIAO** [comment]
thank you，i will try to reprocess data again and try evaluation again

**Comment by YhQIAO** [comment]
I tried processing the data again and running it again, but I still get the exact same error message. Could it be that some parameters have been modified during Nuscene's data preprocessing (e.g. options file)?

**Comment by YhQIAO** [comment]
![image](https://github.com/user-attachments/assets/ac86e843-f66a-411c-8fac-aa15eaf400bb)
the dimension of processed nuscene images and pointcloud is shown in image

**Comment by martin-liao** [comment]
Ohhhhh... Image size should be (H, W)=(320, 640) instead of (160, 320).
I will check the data pre-processing code.

**Comment by martin-liao** [comment]
Please set the ``img_scale`` to 0.4 instead of 0.2 [here](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/data/options.py#L71).
I will update the code later.

**Comment by martin-liao** [comment]
If you still have any questions, please feel free to contact me.

**Comment by YhQIAO** [comment]
Thank you for your patience, I will close this issue after I try to run it successfully.
