### ISSUE TITLE
A weird problem about GPU memory usage

### ISSUE THREAD

**Issue by YhQIAO** [WHU-USI3DV/CoFiI2P#13]
if i change batch_size in eval_all.py as 2, There will be the following error
![image](https://github.com/user-attachments/assets/de8f3907-7458-4157-aa56-b3c9447ca915)
Increasing the batch_sizes will increase the memory usage, but 1200GB is very abnormal.
I found that the batch_size in the training stage is also 1 (I haven't run the train code yet). Will this problem occur if the batch size is set to be greater than 1 on your computer?

**Comment by martin-liao** [comment]
Due to the GPU memory limitation, we trained the model with batch_size=1 in our experiments.
I will work on solving the issues caused by increasing the batch size.

**Comment by martin-liao** [comment]
As we follow the KPConv implementation of Geotransformer [here](https://github.com/qinzheng93/GeoTransformer/issues/36), CoFiI2P only supports ``batch_size=1`` now.
We will try our best to support ``batch_size >1``shortly.
