### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by FDZ-XL** [WHU-USI3DV/CoFiI2P#14]
I have installed the corresponding torch and open3d as per your request, and currently the code has the following error: 

Traceback (most recent call last):
  File "C:\Users\27248\Desktop\codeupdate\0912\CoFiI2P-main\train.py", line 14, in <module>
    from data.kitti import kitti_pc_img_dataset
  File "C:\Users\27248\Desktop\codeupdate\0912\CoFiI2P-main\data\kitti.py", line 18, in <module>
    from model.kpconv.preprocess_data import precompute_point_cloud_stack_mode, precompute_point_cloud_cuda
  File "C:\Users\27248\Desktop\codeupdate\0912\CoFiI2P-main\model\kpconv\preprocess_data.py", line 4, in <module>
    from open3d.ml.torch.layers import FixedRadiusSearch, KNNSearch
  File "C:\Users\27248\anaconda3\envs\dlpeizhun\lib\site-packages\open3d\ml\torch\__init__.py", line 15, in <module>
    raise Exception('Open3D was not built with PyTorch support!')
Exception: Open3D was not built with PyTorch support!

I would like to ask if you know what caused this error. Is there any library that I haven't installed yet?

**Comment by martin-liao** [comment]
Did you install the open3d with ``pip install open3d==0.17.0``?
I think this [blog](https://stackoverflow.com/questions/65794655/open3d-ml-and-pytorch) may help you.
Besides, we recommend using a Linux system instead of a Windows system for training and evaluation.

**Comment by FDZ-XL** [comment]
> Did you install the open3d with `pip install open3d==0.17.0`? I think this [blog](https://stackoverflow.com/questions/65794655/open3d-ml-and-pytorch) may help you. Besides, we recommend using a Linux system instead of a Windows system for training and evaluation.

Thank you for your answer. I have installed pytorch=1.13.1 and open3d=0.17.0 on the Windows operating system, but this issue still persists. May I ask what operating system you are using here? Is it Windows or Ubuntu? Is my error related to the Windows operating system? Thank you for your reply. Looking forward to hearing back from you again.

**Comment by martin-liao** [comment]
ubuntu20.04

**Comment by FDZ-XL** [comment]
thank you very much

**Comment by martin-liao** [comment]
Since the problem has been resolved, I will close the issue.
