### ISSUE TITLE
Demo Required

### ISSUE THREAD

**Issue by qsisi** [WHU-USI3DV/CoFiI2P#16]
Hi! Thanks for open-sourcing this amazing project.

I was wondering if you could provide a demo for the registration of the image and the corresponding point cloud? That would make the use of this project more easier.

Thanks.

**Comment by martin-liao** [comment]
Thanks for your interest. We are busy with another project now. Additional code for visualization will be provided later.
 [Demo](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/vis_nuscenes_pose.ipynb) for visualizing the point cloud on the image plane is available.
