### ISSUE TITLE
Paid 300 RMB request code assistance

### ISSUE THREAD

**Issue by FDZ-XL** [WHU-USI3DV/CoFiI2P#17]
I have almost finished reading all the code you provided, although all the code can be understood and run, I cannot understand some of its specific meanings. So, I would like to pay you 300 RMB and hope you can take 1 to 2 hours. I would like to ask you some questions about the code and hope you can give me some inspiration. I'm not sure if you agree, but if you're willing, please add me on WeChat: z1813914689. Wishing you a happy life!

**Comment by martin-liao** [comment]
We believe that Github is a voluntary open-source platform and we will try our best to respond to any questions from those interested. **Everything is free.**
If you still have any questions, please submit an issue or contact me. The email address is ``martin_liao@whu.edu.cn``.
