### ISSUE TITLE
Regarding the final result.

### ISSUE THREAD

**Issue by LoveMYChen** [WHU-USI3DV/CoFiI2P#2]
Hello, I have downloaded your training model and Kitti dataset, and conducted model evaluation. I have obtained some numbers, but the problem now is that I am not sure how to use these numbers. My ultimate goal is to adjust the camera pose using my own dataset. Can you give me some guidance?

**Comment by kang-1-2-3** [comment]
The eval_all.py produces the result on rotation and translation error. You can load the files and calculate statistics of them. The calc_result.py give the example for specific threshold of these errors. Hopes that it helps you.

**Comment by LoveMYChen** [comment]
Can we use some algorithm to calculate the correct pose after obtaining errors in rotation and translation? Do you have any recommended algorithms?

**Comment by martin-liao** [comment]
Since the problem has been resolved, I will close the issue.
