### ISSUE TITLE
Questions about pred_P

### ISSUE THREAD

**Issue by max2857** [WHU-USI3DV/CoFiI2P#21]
Hello, I noticed that the Pred_P is related to the randomly generated GT_P. How can I predict the similar external parameters as in the dataset labels（when P_Tr is unknown).

**Comment by martin-liao** [comment]
You may be referring to the prediction of extrinsic parameters  during inference.
During inference, the network constructs the point/pixel descriptors and solves the 6-DoF extrinsic parameters using RANSAC-PNP. GT labels are not required.

**Comment by max2857** [comment]
But I see that you have already projected the lidar point cloud onto the camera coordinate system using the extrinsic parameters P_Tr in the label when processing the Kitti/Nuscenes dataset, and the transformed pc is used for inference. If I want to predict the actual extrinsic parameters(like pred_P_Tr) instead of the Pred_P corresponding to the randomly generated GT_P, should I have the point cloud in its own coordinate system instead of using P_Tr for projection?

**Comment by kang-1-2-3** [comment]
If you want to use the real external parameters as ground truth when testing, the dataloader should be modified, i.e., delete the random projection part.

**Comment by kang-1-2-3** [comment]
Without random transformation, lidar_pc should be processed in the original coordinate system, that makes the ground truth transformation equal to the extrinsic parameters in KITTI dataset. But for Nuscenes, I think you need to regenerate the dataset because when we processed Nuscenes, we have projected the pc to camera coordinate system, so the processed Nuscenes does not contain the real extrinsic parameters provided by Nuscenes.

**Comment by kang-1-2-3** [comment]
We project pc to camera coordinate system just for using random transformation as gt in the following, you don't have to make transformations to pc if you want to use the ground truth provided by original dataset.

**Comment by max2857** [comment]
ok， thanks for your swift reply

**Comment by max2857** [comment]
I tried to use the P_Tr on the regenerated nuscenes dataset (no transformation to pc), but the predicted results were poor. The angles-diff can reach about 90 when compared to P_Tr。 Have you ever tried this?

**Comment by dom-lee** [comment]
@martin-liao The predicted results with the increased `P_t*_amplitude` (e.g., 1m) also generate poor results. Is the current model is not robust when pointcloud and image are not in the same coordinates?

**Comment by martin-liao** [comment]
> [@kang-1-2-3](https://github.com/kang-1-2-3) [@martin-liao](https://github.com/martin-liao) The predicted results with the increased `P_t*_amplitude` (e.g., 1m) also generate poor results. Is the current model is not robust when pointcloud and image are not in the same coordinates?

Could you provide the ``P_t*_amplitude`` settings and evaluation results?
Large translation distortion lowers the image-point cloud overlapping rate, potentially degrading registration accuracy.

**Comment by martin-liao** [comment]
Sorry for the late reply. In the ``generate_random_transform`` [function](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/data/kitti.py#L216), ``P_tx``, ``P_ty``, and ``P_tz`` determine the range of random translations of point cloud from the **camera coordinate system**. 
Intuitively, the overlapping ratio will be lower when the point cloud is far from the camera coordinate system.
