### ISSUE TITLE
How to apply this method on your own data set？

### ISSUE THREAD

**Issue by crzzx1** [WHU-USI3DV/CoFiI2P#3]
Recently, I have processed our data set into the format required by CorrI2P, but I have never been able to get a valid pre-training package during the training phase (is_success always solves the error). Now I plan to switch to your method for testing. Is there anything I need to pay special attention to? Thanks!

**Comment by daruiboom** [comment]
Hello, I have a question to ask you. Is this model suitable for a single non sequential dataset

**Comment by crzzx1** [comment]
> 你好，我有一个问题要问你。此模型是否适用于单个非序列数据集

单个非序列数据集？

**Comment by daruiboom** [comment]
kitti是以序列为组的逐帧图，我的数据集就是单独个体这样子

**Comment by kang-1-2-3** [comment]
> Recently, I have processed our data set into the format required by CorrI2P, but I have never been able to get a valid pre-training package during the training phase (is_success always solves the error). Now I plan to switch to your method for testing. Is there anything I need to pay special attention to? Thanks!

Actually we use the same dataset structure as CorrI2P, if your dataset can not be used on CorrI2P, it probably also can not be used on CoFiI2P. There are some things that you should pay attention for testing with our network, like the number of point cloud should better be 20480. 

There is one thing that may lead to unsuccessful test on CorrI2P is the dataloader. They have preprocessed their dataset, so you may pay attention to the relationship between point cloud, camera and image, i.e., make sure you have the right transformation.

**Comment by kang-1-2-3** [comment]
> kitti是以序列为组的逐帧图，我的数据集就是单独个体这样子

**Comment by kang-1-2-3** [comment]
> kitti是以序列为组的逐帧图，我的数据集就是单独个体这样子

**Comment by kang-1-2-3** [comment]
> kitti是以序列为组的逐帧图，我的数据集就是单独个体这样子

Our network does not relate to sequence data input, however the dataset are split with sequence. If you want to use your own data, you may modify the dataloader.
