### ISSUE TITLE
How to set the threshold

### ISSUE THREAD

**Issue by honghullw** [WHU-USI3DV/CoFiI2P#4]
Hello！ May I ask if the threshold mentioned in your paper refers to setting it in the code?
![image](https://github.com/WHU-USI3DV/CoFiI2P/assets/62421717/fc87a2c5-5bc3-40a3-b8d6-c6e626009e03)
![image](https://github.com/WHU-USI3DV/CoFiI2P/assets/62421717/348f12fd-afe4-4103-a68d-a9e2207dc425)

**Comment by kang-1-2-3** [comment]
These refers to point cloud augmentation, not the threshold for evaluate the test result.

**Comment by honghullw** [comment]
Thank you for your answer. So where should I set the threshold for evaluating test results in the code to achieve the effects described in the paper?
![image](https://github.com/user-attachments/assets/64f4ae45-f0f2-409f-8789-f4ea06cd3a30)

**Comment by kang-1-2-3** [comment]
You should use eval_all.py to load checkpoint and save test result. Then use calc_result.py to load test result, set threshold and evaluate the result with threshold.

**Comment by honghullw** [comment]
I understand, thank you very much for your answer.

**Comment by martin-liao** [comment]
Since the problem has been resolved, I will close the issue.
