### ISSUE TITLE
the script file for calculating metrics

### ISSUE THREAD

**Issue by honghullw** [WHU-USI3DV/CoFiI2P#8]
Hello! Could you please provide the script file for calculating these metrics? I'm not sure how to calculate these.
![image](https://github.com/user-attachments/assets/d0eb8c6a-e279-4f1b-8f0a-81b460f5a5b3)

**Comment by martin-liao** [comment]
Thanks for your interest. 
We do not currently provide the script because the frustum classification results have been removed in the newest [version](https://arxiv.org/abs/2309.14660v4). Please refer to the newest version of the manuscript for details.

**Comment by honghullw** [comment]
Thank you for your response. Do you have a script for calculating RR? 
![image](https://github.com/user-attachments/assets/e337815e-c983-407a-bf8a-cf8ad6bf2e89)

**Comment by martin-liao** [comment]
[link](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/evaluation/calc_result.py#L9)
Success rate and RR refer to the same concept.

**Comment by honghullw** [comment]
I understand. Thank you very much for your patient response!

**Comment by martin-liao** [comment]
Since the problem has been resolved, I will close the issue.
